#!/bin/bash

# cd /sdcard/acode/otfo/ ; bash sh_compress



echo "开始压缩 _site 目录中的文件..."

# 压缩 HTML 文件
find _site -type f -name "*.html" | while read -r file; do
  # 跳过以 /s/ 开头的短链接网页
  if echo "$file" | grep -q "/s/"; then
    echo "跳过压缩: $file"
    continue
  fi
  echo "正在压缩 HTML: $file"
  html-minifier --collapse-whitespace --remove-comments --minify-css true --minify-js true -o "$file" "$file"
done

# 压缩 CSS 文件
find _site -type f -name "*.css" | while read -r file; do
  echo "正在压缩 CSS: $file"
  cssnano "$file" >> temp && mv temp "$file"
done

# 压缩 JS 文件
find _site -type f -name "*.js" | while read -r file; do
  echo "正在压缩 JS: $file"
  terser --compress --mangle -o "$file" -- "$file"
done

# 压缩 JSON 文件
find _site -type f -name "*.json" | while read -r file; do
  echo "正在压缩 JSON: $file"
  temp_file=$(mktemp) # 创建临时文件
  jq -c . "$file" > "$temp_file" && mv "$temp_file" "$file"
done

echo "所有文件已压缩完成！"

