
url: "https://otfo.cc"
baseurl: "/bny"

title: Bny
author: Bny
logo: /assets/img/logo.jpg
description: "　本站记录一些关于“饥荒手游模组”的资料，为船难单机版(ShipWrecked)使用模组提供技术支持。"

# google_analytics:

# theme: jekyll-theme-minimal

plugins:
  - jekyll-admin
  - jekyll-assets
  - jekyll-seo-tag

assets:
  compress: true
  cache: false

# paginate: 2
# paginate_path: "/page:num"

defaults:
  - scope:
      path: "_posts"
    values:
      layout: post
      tags: ["other"]