
url: "https://otfo.cc"
baseurl: "/bny"

title: Bny
author: Bny
logo: /assets/img/logo.jpg
# description: "　为船难单机版(ShipWrecked)使用模组提供技术支持。"

# google_analytics:

# theme: jekyll-theme-minimal
# 输出 JSON 文件
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-admin
  - jekyll-assets
  - jekyll-seo-tag

assets:
  compress: true
  cache: false

search:
  enabled: true
  index:
    posts: true

# paginate: 2
# paginate_path: "/page:num"

defaults:
  - scope:
      path: "_posts"
    values:
      layout: post
      tags: ["other"]
  - scope:
      path: ""
      type: "json"
    values:
      layout: null