#!/bin/bash

# cd /sdcard/acode/otfo/ ; bash sh_deploy

# 网页子目录
dir="b"

# 设置远端仓库
# git remote set-url origin https://github.com/cnzixn/otfo.cc.git

# 新建一个本地仓库，并设置远端仓库
# git init
# git remote add origin https://github.com/cnzixn/otfo.cc.git

# 切换到主分支，构建站点并提交更改
git checkout -b master
git checkout master

# 构建站点
jekyll build

# 添加文件，提交
git add .
git commit -m "Update master at $(date '+%Y-%m-%d %H:%M:%S')"
git push origin master --force

# 压缩网站
bash ./$dir/sh_compress

# 切换到 gh-pages 分支，清空内容
git checkout -b gh-pages
git checkout gh-pages
git rm -rf .

# 将 _site 文件夹内容复制到 gh-pages 分支根目录
git checkout master -- CNAME
git checkout master -- _site
cp -r ./_site "./$dir"
cp -r "./$dir/s" .
cp "./$dir/index.html" .
cp "./$dir/404.html" .
git rm -rf deploy.sh
git rm -rf start.sh
git rm -rf _site

# 提交并推送到 gh-pages 分支
git add .
git commit -m "Update gh-pages at $(date '+%Y-%m-%d %H:%M:%S')"
git push origin gh-pages --force
git commit -m "w, not Update gh-pages at $(date '+%Y-%m-%d %H:%M:%S')"

# 返回到主分支
git checkout master


